package Artemis::Remote;

use warnings;
use strict;
use Moose;

extends 'Artemis::Base';
has cfg =>  (is => 'rw', isa => 'HashRef', default => sub {{mcp_port => 7357, mcp_host => 'localhost'}});

sub BUILD
{
        my ($self, $config) = @_;
        $self->{cfg}=$config;
}


=head1 NAME

Artemis::Remote - Common functionality for all remote projects!

=head1 VERSION

Version 0.01

=cut

our $VERSION = '1.000024';


=head2 get_report_file

Generate the file name for communication with MCP. To make MCP
restartable we need to keep all status messages that any remote system
wants to send while the MCP is not available. This is achieved by
writing the status messages into the file generated by this method.

The file name of the report file is put into the provided config as
under the has key {files}->{report_file}.

@param hash ref - config without report file option

@return success - config with report file option
@return error   - error string

=cut

# This function resided in Remote.pm because both Config and Net make
# use of it. Config, because that's part of the module's job, Net as
# a backup just in case setting in Config went wrong.
sub get_report_file
{
        my ($self, $config) = @_;
        my $report_dir .= $config->{paths}{output_dir};
        $report_dir    .= $config->{test_run};
        $report_dir    .= "/report/";
        $report_dir    .= "guest-".$config->{guest_number}."/" if $config->{guest_number};
        my $retval      = $self->makedir ($report_dir);
        return $retval if $retval;
        $config->{files}{report_file} = "$report_dir/report_file";
        return $config;
}


=head1 SYNOPSIS

This module contains functions that are equal for all remote Artemis
projects (currently Artemis::PRC and Artemis::Installer).
Artemis::Remote itself does not export functionality but instead is the
base image for all modules of the project.

=head1 EXPORT

Nothing. 

=head1 FUNCTIONS

=head1 AUTHOR

OSRC SysInt Team, C<< <osrc-sysint at elbe.amd.com> >>

=head1 BUGS


=head1 COPYRIGHT & LICENSE

Copyright 2010 OSRC SysInt Team, all rights reserved.

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.


=cut

1; # End of Artemis::Remote
